// characters.js
const charactersData = [
  { chinese: '你', english: 'You', words: ['你好 - Hello', '你们 - You all'] },
  { chinese: '好', english: 'Good', words: ['很好 - Very good', '好吃 - Delicious'] },
  { chinese: '早', english: 'Morning', words: ['早上 - Morning', '早饭 - Breakfast'] },
  { chinese: '巴', english: 'Ba', words: ['巴士 - Bus', '巴西 - Brazil'] },
  { chinese: '干', english: 'Dry', words: ['干净 - Clean', '干杯 - Cheers'] },
  { chinese: '几', english: 'Several', words: ['几个 - Several', '几天 - Several days'] },
  { chinese: '打', english: 'Hit', words: ['打篮球 - Play basketball', '打电话 - Make a call'] },
  { chinese: '元', english: 'Yuan', words: ['人民币 - Chinese yuan', '元旦 - New Year\'s Day'] },
  { chinese: '厂', english: 'Factory', words: ['工厂 - Factory', '电厂 - Power plant'] },
  { chinese: '目', english: 'Eye', words: ['眼睛 - Eyes', '目标 - Goal'] },
  { chinese: '见', english: 'See', words: ['看见 - See', '见面 - Meet'] },
  { chinese: '禾', english: 'Grain', words: ['稻禾 - Rice', '小麦 - Wheat'] },
  { chinese: '自', english: 'Self', words: ['自己 - Self', '自行车 - Bicycle'] },
  { chinese: '己', english: 'Self', words: ['自己 - Self', '本人 - Myself'] },
  { chinese: '爱', english: 'Love', words: ['爱情 - Love', '爱心 - Love and care'] },
  { chinese: '这', english: 'This', words: ['这个 - This', '这样 - Like this'] },
  { chinese: '奶', english: 'Milk', words: ['牛奶 - Milk', '豆奶 - Soy milk'] },
  { chinese: '块', english: 'Piece', words: ['一块 - One piece', '一块钱 - One yuan'] },
  { chinese: '那', english: 'That', words: ['那个 - That', '那里 - There'] },
  { chinese: '哪', english: 'Which', words: ['哪个 - Which', '哪里 - Where'] },
  { chinese: '谢', english: 'Thanks', words: ['谢谢 - Thank you', '感谢 - Gratitude'] },
  { chinese: '想', english: 'Want', words: ['想要 - Want', '想念 - Miss'] },
  { chinese: '它', english: 'It', words: ['它是 - It is', '它们 - They'] },
  { chinese: '发', english: 'Hair', words: ['头发 - Hair', '发现 - Discover'] },
  { chinese: '弟', english: 'Younger Brother', words: ['弟弟 - Younger brother', '大弟子 - Senior disciple'] },
  { chinese: '鼻', english: 'Nose', words: ['鼻子 - Nose', '鼻涕 - Nasal mucus'] },
  { chinese: '阳', english: 'Sun', words: ['阳光 - Sunlight', '阳台 - Balcony'] },
  { chinese: '哭', english: 'Cry', words: ['哭泣 - Cry', '笑而不哭 - Keep smiling'] },
  { chinese: '肚', english: 'Stomach', words: ['肚子 - Stomach', '腹肌 - Abdominal muscle'] },
  { chinese: '脸', english: 'Face', words: ['脸部 - Face', '脸色 - Facial expression'] },
  { chinese: '半', english: 'Half', words: ['半天 - Half a day', '半个小时 - Half an hour'] },
  { chinese: '又', english: 'Again', words: ['又见面 - Meet again', '又高又帅 - Tall and handsome'] },
  { chinese: '朵', english: 'Flower', words: ['花朵 - Flower', '一朵云 - A cloud'] },
  { chinese: '午', english: 'Noon', words: ['中午 - Noon', '午餐 - Lunch'] },
  { chinese: '包', english: 'Wrap', words: ['包裹 - Package', '包子 - Steamed bun'] },
  { chinese: '分', english: 'Minute', words: ['分钟 - Minute', '分数 - Score'] },
  { chinese: '平', english: 'Flat', words: ['平常 - Usually', '平地 - Flat ground'] },
  { chinese: '把', english: 'Hold', words: ['拿把伞 - Hold an umbrella', '把手 - Handle'] },
  { chinese: '笑', english: 'Smile', words: ['微笑 - Smile', '大笑 - Laugh'] },
  { chinese: '着', english: 'On', words: ['穿着 - Wearing', '坐着 - Sitting'] },
  { chinese: '看', english: 'Look', words: ['看书 - Read a book', '看电影 - Watch a movie'] },
  { chinese: '会', english: 'Can', words: ['会说 - Can speak', '会员 - Member'] },
  { chinese: '球', english: 'Ball', words: ['足球 - Football', '篮球 - Basketball'] },
  { chinese: '形', english: 'Shape', words: ['形状 - Shape', '形容 - Describe'] },
  { chinese: '方', english: 'Square', words: ['方向 - Direction', '方法 - Method'] },
  { chinese: '正', english: 'Correct', words: ['正确 - Correct', '正常 - Normal'] },
  { chinese: '灯', english: 'Lamp', words: ['台灯 - Desk lamp', '电灯 - Electric light'] },
  { chinese: '抱', english: 'Hug', words: ['拥抱 - Hug', '抱歉 - Sorry'] },
  { chinese: '要', english: 'Want', words: ['要求 - Request', '需要 - Need'] },
  { chinese: '吃', english: 'Eat', words: ['吃饭 - Eat a meal', '吃早餐 - Eat breakfast'] },
  { chinese: '香', english: 'Fragrant', words: ['花香 - Floral fragrance', '香水 - Perfume'] },
  { chinese: '穿', english: 'Wear', words: ['穿衣服 - Wear clothes', '穿越 - Travel through'] },
  { chinese: '亮', english: 'Bright', words: ['明亮 - Bright', '发亮 - Shine'] },
  { chinese: '今', english: 'Today', words: ['今天 - Today', '今后 - From now on'] },
  { chinese: '明', english: 'Bright', words: ['明白 - Understand', '明天 - Tomorrow'] },
  { chinese: '兴', english: 'Interest', words: ['兴趣 - Interest', '高兴 - Happy'] },
  { chinese: '空', english: 'Empty', words: ['空气 - Air', '空间 - Space'] },
  { chinese: '很', english: 'Very', words: ['很高兴 - Very happy', '很多 - Many'] },
  { chinese: '园', english: 'Garden', words: ['公园 - Park', '花园 - Garden'] },
  { chinese: '先', english: 'First', words: ['先生 - Mister', '首先 - First'] },
    // Add more characters and their data here
  ];
  
window.charactersData = charactersData;
  